import XCTest
import FSRS
@testable import VocabFolio

/// Proves the iOS scheduler lands on the same dates as the web app: the
/// vectors were generated by ts-fsrs 5.4.2 (FSRS-6 defaults) and replayed
/// here through swift-fsrs with the app's parameters.
final class FSRSParityTests: XCTestCase {
    struct Vectors: Decodable { let t0: String; let scenarios: [String: [Step]] }
    struct Step: Decodable {
        let now: String
        let rating: Int
        let options: [String: CardJSON]
        let result: CardJSON
        let log: LogJSON
    }
    struct CardJSON: Decodable {
        let due: String
        let stability: Double
        let difficulty: Double
        let elapsed_days: Double
        let scheduled_days: Double
        let learning_steps: Int
        let reps: Int
        let lapses: Int
        let state: Int
        let last_review: String?
    }
    struct LogJSON: Decodable { let elapsed_days: Double; let scheduled_days: Double; let state: Int }

    private let iso: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    func testSchedulerMatchesReferenceVectors() throws {
        let url = try XCTUnwrap(Bundle(for: FSRSParityTests.self).url(forResource: "fsrs-vectors", withExtension: "json"))
        let vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
        let fsrs = FSRSScheduler.fsrs
        XCTAssertEqual(fsrs.parameters.w.count, 21, "FSRS-6 parameters expected")

        for (name, steps) in vectors.scenarios {
            var card = Card(due: try XCTUnwrap(iso.date(from: vectors.t0)), state: .new)
            for (i, step) in steps.enumerated() {
                let now = try XCTUnwrap(iso.date(from: step.now))
                let where_ = "\(name) · step \(i)"
                let preview = try fsrs.`repeat`(card: card, now: now)
                for r in [Rating.again, .hard, .good, .easy] {
                    let expected = try XCTUnwrap(step.options[String(r.rawValue)], where_)
                    let got = try XCTUnwrap(preview[r], where_).card
                    assertCard(got, expected, "\(where_) · option \(r.stringValue)")
                }
                let rating = try XCTUnwrap(Rating(rawValue: step.rating))
                let res = try fsrs.next(card: card, now: now, grade: rating)
                assertCard(res.card, step.result, "\(where_) · result")
                XCTAssertEqual(res.log.elapsedDays, step.log.elapsed_days, accuracy: 1e-9, where_)
                XCTAssertEqual(res.log.scheduledDays, step.log.scheduled_days, accuracy: 1e-9, where_)
                card = res.card
            }
        }
    }

    private func assertCard(_ got: Card, _ exp: CardJSON, _ ctx: String) {
        let expDue = iso.date(from: exp.due)?.timeIntervalSince1970 ?? -1
        XCTAssertEqual(got.due.timeIntervalSince1970, expDue, accuracy: 1.0, ctx + " due")
        XCTAssertEqual(got.stability, exp.stability, accuracy: max(1e-6, abs(exp.stability) * 1e-6), ctx + " stability")
        XCTAssertEqual(got.difficulty, exp.difficulty, accuracy: max(1e-6, abs(exp.difficulty) * 1e-6), ctx + " difficulty")
        XCTAssertEqual(got.elapsedDays, exp.elapsed_days, accuracy: 1e-9, ctx + " elapsed")
        XCTAssertEqual(got.scheduledDays, exp.scheduled_days, accuracy: 1e-9, ctx + " scheduled")
        XCTAssertEqual(got.learningSteps, exp.learning_steps, ctx + " learningSteps")
        XCTAssertEqual(got.reps, exp.reps, ctx + " reps")
        XCTAssertEqual(got.lapses, exp.lapses, ctx + " lapses")
        XCTAssertEqual(got.state.rawValue, exp.state, ctx + " state")
    }

    /// Round-tripping through the compact `c` representation must not move a card.
    func testCompactCardRoundTrip() throws {
        let fsrs = FSRSScheduler.fsrs
        var word = Word(ru: "вода", ac: "вода'", en: "water", pos: "n", t: Date().timeIntervalSince1970 * 1000)
        let first = try fsrs.next(card: FSRSScheduler.card(for: word), now: Date(), grade: .good)
        word.c = FSRSScheduler.data(from: first.card)
        let back = FSRSScheduler.card(for: word)
        XCTAssertEqual(back.due.timeIntervalSince1970, first.card.due.timeIntervalSince1970, accuracy: 0.001)
        XCTAssertEqual(back.stability, first.card.stability, accuracy: 1e-9)
        XCTAssertEqual(back.difficulty, first.card.difficulty, accuracy: 1e-9)
        XCTAssertEqual(back.state, first.card.state)
        XCTAssertEqual(back.reps, first.card.reps)
        XCTAssertEqual(back.learningSteps, first.card.learningSteps)
        XCTAssertEqual(back.lastReview?.timeIntervalSince1970 ?? 0, first.card.lastReview?.timeIntervalSince1970 ?? 0, accuracy: 0.001)
    }
}
